### ISSUE TITLE
Lookup error

### ISSUE THREAD

**Issue by Kongledyret** [shoekla/Find-Me-Movies#1]
Hi! 

I tried the demo and also setup it in my own heruko. When searching it only displays a lot of P: and when I press one of them I get a random movie. 

Any idea?

**Comment by shoekla** [comment]
Hey!
Thanks for bringing that issue to me, I will try to fix it, its probably a change in code format in the website I scrape the movie info from. I will let you know when it is fixed.
Thanks again!

**Comment by shoekla** [comment]
Hey, I made it a download app now, so the issues are fixed, downloading the app is really simple and works for both mac and windows! Thanks!
